# Generated by Django 5.2 on 2025-04-16 01:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shopping_carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_carts.shoppingcart')),
            ],
            options={
                'db_table': 'shopping_cart_products',
                'unique_together': {('shopping_cart', 'product')},
            },
        ),
    ]
